### ISSUE TITLE
Update spartakus docs to reflect kustomize

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#1084]
The instructions
https://www.kubeflow.org/docs/other-guides/usage-reporting/

Need to be updated for kustomize.

To prevent Spartakus from being deployed; users should do the following before running `kfctl apply`.

* Edit ${KFAPP}/app.yaml
* Delete the entry in KfDef.Spec.Applications for spartakus

  ```
    - kustomizeConfig:
      parameters:
      - initRequired: true
        name: usageId
        value: "7439583937720421527"
      - initRequired: true
        name: reportUsage
        value: "true"
      repoRef:
        name: manifests
        path: common/spartakus
    name: spartakus
  ```

see for example 
https://github.com/kubeflow/kubeflow/blob/f32b3ee37f2649f2a8c72d80b46ed9eb92370594/bootstrap/config/kfctl_gcp_iap.yaml#L158

I think we can delete the section

>You can improve the quality of the data by giving each Kubeflow deployment a unique id by editing spartakus.yaml in your KF_APP directory:..

Those instructions are outdated. If users want to customize their id they can edit usageId in KfDef.Spec.applications before running generate

See also: kubeflow/kubeflow#3605

@xauthulei any chance you could pick this up
