### ISSUE TITLE
Document customizing various fields in a KfDef configuration

### ISSUE THREAD

**Issue by krishnadurai** [kubeflow/website#1442]
It would be great to have a doc entailing the structure of KfDef and the fields it supports. This may turn out to be a manual on *How to edit a KfDef?*

*Applications*
```
  applications:
  - kustomizeConfig:
      overlays:
      parameters:
      repoRef:
        name:
        path:
    name:
```

Especially a user might want to modify or configure the URIs of upstream repositories within fields.

*Repos*
```
  repos:
  - name: manifests
    uri: https://github.com/kubeflow/manifests/archive/master.tar.gz
```
