### ISSUE TITLE
Authenticating Kubeflow to GCP

### ISSUE THREAD

**Issue by dlahlou** [kubeflow/website#1476]
https://www.kubeflow.org/docs/gke/authentication/

In [starting-in-kubeflow-v0-7-google-kubernetes-engine-gke-workload-identity](https://www.kubeflow.org/docs/gke/authentication/#starting-in-kubeflow-v0-7-google-kubernetes-engine-gke-workload-identity), step 4 : **Manually create a profile for user1 and specify the GCP service account to bind in plugins field**, I believe the yaml text is not well indented, it should probably look like the following : 

```
apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
 name: profileName
 spec:
 owner:
  name: user1@email.com
  plugins:
  - kind: WorkloadIdentity
  spec:
   gcpServiceAccount: user1-gcp@project-id.iam.gserviceaccount.com
```
