### ISSUE TITLE
[AWS] OIDC authentication example

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/website#1672]
Manifest https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_aws_cognito.v1.0.0.yaml
uses Cognito on ALB for authentication. Based on our observation, a group of users like to use OIDC directly on ALB instead of via Coginito.

We want to give an example to use Github Login.

**Comment by Jeffwan** [comment]
https://github.com/kubeflow/manifests/issues/945 this issue has been resolved and this can be unblocked.

**Comment by Jeffwan** [comment]
@PatrickXYS 

Connect Github to Auth0,
https://auth0.com/docs/connections/social/github

Setup up ALB with Auth0,
https://medium.com/@sandrinodm/securing-your-applications-with-aws-alb-built-in-authentication-and-auth0-310ad84c8595

With this, you can successfully setup auth flow from ALB -> Auth0 -> Github, I tested it and it's working, need you to help on the doc change. Here's an example on ALB changes

![image](https://user-images.githubusercontent.com/4739316/75480927-04749f00-5957-11ea-9590-27fc75ba3d38.png)

**Comment by Jeffwan** [comment]
```
oidc:
    oidcIssuer: https://kubeflow.auth0.com/
    oidcAuthorizationEndpoint: https://kubeflow.auth0.com/authorize
    oidcTokenEndpoint: https://kubeflow.auth0.com/oauth/token
    oidcUserInfoEndpoint: https://kubeflow.auth0.com/userinfo
    certArn: arn:aws:cognito-idp:us-west-2:xxxxxx:userpool/us-west-2_DtjdVUviC
    oAuthClientId: yours
    oAuthClientSecret: yours
```

**Comment by PatrickXYS** [comment]
One issue here: 

```
oidc:
    oidcIssuer: https://kubeflow.auth0.com/
    oidcAuthorizationEndpoint: https://kubeflow.auth0.com/authorize
    oidcTokenEndpoint: https://kubeflow.auth0.com/oauth/token
    oidcUserInfoEndpoint: https://kubeflow.auth0.com/userinfo

    # this should be ACM's certArn rather than cognito user pool arn
    certArn: arn:aws:cognito-idp:us-west-2:xxxxxx:userpool/us-west-2_DtjdVUviC 

    oAuthClientId: yours
    oAuthClientSecret: yours
```
