### ISSUE TITLE
Pipeline Metrics file_output not explained

### ISSUE THREAD

**Issue by GraphtyLove** [kubeflow/website#2021]
https://www.kubeflow.org/docs/pipelines/sdk/pipelines-metrics/

I just passed a whole day to understand why the metrics were not shown in the UI after my pipeline. 
In fast (using ContainerOps) you need to define a `file_outputs`. That is not said in the documentation and the information is quite hard to find. 

You should declare your step as follow:

```python
operations['your_step'] = dsl.ContainerOp(
        name = 'step_2',
        image = '<IMAGE_NAME_HERE>:<IMAGE_TAG_HERE>,
        command = ['python'],
        arguments = [
            'your_step.py'
        ],
        file_outputs = {
            'mlpipeline-metrics': '/mlpipeline-metrics.json'
        }
    )
```

I really think it should be explained in the doc somewhere on the metrics page or at least have a link to the explanation on this page. And that's the same for the output viewer, the process is the same and the explanation is not here too.

**Comment by matphilippe** [comment]
This issue is relevant outside of the scope of `ContainerOps`.
In the .yaml files defining `components`, it looks like we need to specify dedicated `outputs` and `fileOutputs`, as shown below:
````yaml
  outputs:
  - { name: MLPipeline Metrics, type: Metrics }
  # Other outputs
  implementation:
   container: ...
    image: ...
    command: ...
    args:  ...
    fileOutputs:
        MLPipeline Metrics: /mlpipeline-metrics.json
````
I got this from the [confusion matrix example](https://github.com/kubeflow/pipelines/blob/master/components/local/confusion_matrix/).

In this regards, the text about `fileOutputs` in the [kubeflow component specification section](https://www.kubeflow.org/docs/pipelines/reference/component-spec/#implementation) is a bit misleading, at it hints that the user is unlikely to have to rely on this field when defining components.

**Comment by Ark-kun** [comment]
> In the .yaml files defining `components`, it looks like we need to specify dedicated `outputs` and `fileOutputs`, as shown below:
> In this regards, the text about fileOutputs in the kubeflow component specification section is a bit misleading, at it hints that the user is unlikely to have to rely on this field when defining components.

There is no contradiction. The confusion matrix is a really old component and the effort to fix it started back in 2018. https://github.com/kubeflow/pipelines/pull/580/files#diff-a65b15d94e67f77a796e4940651e5c62

Here is how the component.yaml should look like:
```
  outputs:
  - { name: MLPipeline Metrics, type: Metrics }
  # Other outputs
  implementation:
   container: ...
    image: ...
    command: ...
    args:
    - ...
    - --metrics-path
    - {outputPath: MLPipeline Metrics}
```
