### ISSUE TITLE
Provide options to use IBM Cloud AppID as authentication provider

### ISSUE THREAD

**Issue by shawnzhu** [kubeflow/website#2182]
This is a follow up of #2069 and #2000 

## Today

It uses dex as OIDC auth provider.

## Expected outcome

It provides configuration path to use [IBM Cloud AppID](https://www.ibm.com/cloud/app-id) as OIDC auth provider besides dex.

**Comment by shawnzhu** [comment]
## Requirement

In order to bring in IBM Cloud AppID as a replacement of Dex, it will need to work with existing component called _oidc-authservice_ of multi-user Kubeflow from https://github.com/arrikto/oidc-authservice it's technically working now with its previous release, but more work required ONLY if we want to integrate with latest release of [arrikto/oidc-authservice](https://github.com/arrikto/oidc-authservice).

## Option 1

upgrade [arrikto/oidc-authservice](https://github.com/arrikto/oidc-authservice) to latest
* break change - rework logout feature of kubeflow central dasbhoard w/ CSRF protection
    * deprecating `X-Auth-Token` header with `Authorization` - https://github.com/kubeflow/kubeflow/issues/5302
* tweak settings in kubeflow/manifests to support this break change

## Option 2

Keep using existing out-dated [arrikto/oidc-authservice](https://github.com/arrikto/oidc-authservice) container image.
* tweak settings of oidc-authservice in kubeflow/manifests repo to favor config settings of IBM AppID.

@animeshsingh @adrian555 @Tomcli comments?

**Comment by shawnzhu** [comment]
## Updates

I've got the AppID works in Kubeflow 1.1 deployed on OpenShift. see my code changes here:
* kfdef - https://github.com/shawnzhu/KubeflowDojo/blob/appid/OpenShift/manifests/kfctl_openshift_tekton_kfserving_appid.v1.1.0.yaml
* Manifests - https://github.com/shawnzhu/manifests/tree/appid

Notice that I've used the option 2 from :point_up: with tweaked settings like:

```YAML
          env:
            - name: USERID_HEADER
              value: kubeflow-userid
            - name: USERID_PREFIX
            - name: USERID_CLAIM
              value: email
            - name: OIDC_PROVIDER
              value: >-
                https://<appid-tenant-url>
            - name: OIDC_AUTH_URL
            - name: OIDC_SCOPES
              value: email
            - name: REDIRECT_URL
              value: >-
                https://<istio-ingressgateway-public-endpoint-FQDN>/login/oidc
            - name: SKIP_AUTH_URI
            - name: PORT
              value: '8080'
            - name: CLIENT_ID
              value: <client_id_from_AppID_service-credential>
            - name: CLIENT_SECRET
              value: <client_secret_from_AppID_service-credential>
```
