### ISSUE TITLE
End-to-end Kubeflow on AWS - cognito ARN typo

### ISSUE THREAD

**Issue by gorinars** [kubeflow/website#2218]
https://www.kubeflow.org/docs/aws/aws-e2e/ has a somewhat confusing description in cognito section:

```
Take note of the following 5 values:
- **The ARN of the certificate from the Certificate Manager of N.Virginia ().**
- The Pool ARN () of the user pool found in Cognito general settings.
- The App client id (), found in Cognito App clients.
- The auth.platform.domain.com as the .
```

then in the KfAwsPlugin config the eu-west-1 certificate is used
```
        cognito:
          certArn: arn:aws:acm:**eu-west-1**:xxxxx:certificate/xxxxxxxxxxxxx-xxxx
          cognitoAppClientId: xxxxxbxxxxxx
          cognitoUserPoolArn: arn:aws:cognito-idp:eu-west-1:xxxxx:userpool/eu-west-1_xxxxxx
          cognitoUserPoolDomain: auth.platform.domain.com
```

It would potentially be less confusing if "The ARN of the certificate from the Certificate Manager of N.Virginia ()." was  replaced with "The ARN of the certificate from the Certificate Manager for ingress-gateway (eu-west-1 in our example)"
