### ISSUE TITLE
kubeflow-gateway.yaml indent is wrong

### ISSUE THREAD

**Issue by jizg** [kubeflow/website#2393]
I found that the indent of  `metadata` and `sepc` fields on `kubeflow-gateway.yaml` on [Securing the Kubeflow authentication with HTTPS](https://www.kubeflow.org/docs/ibm/deploy/authentication/#exposing-the-kubeflow-dashboard-with-dns-and-tls-termination) is wrong. The correct one should be like this:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: kubeflow-gateway
  namespace: kubeflow
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '<hostname>'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
```
