### ISSUE TITLE
Extend instructions on adding a Profile by adding `LimitRange`

### ISSUE THREAD

**Issue by gkcalat** [kubeflow/website#3535]
@jsitu777 thank you for reporting this.

`Profile` controls user workloads to be within the quota. So, if you have a hard quota on CPU and memory it will reject all workloads that do no satisfy it. Unfortunately, it seems that `Container`s without `resources` will also be rejected.

Adding `resources` to the Argo's `workflow-controller-configmap` results in all containers being overwritten and having the same `resources`, which is probably a wrong way to fix the issue described above.

I feel we may have better solutions:
1. Allowing default values in `Profile`, which will be used to fill `resources` for containers that do not have them. This needs to be done in [Profile component](https://github.com/kubeflow/kubeflow/tree/master/components/profile-controller). /cc @kimwnasptd
2. Advising users to create a [LimitRange](https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/) whenever a `Profile` gets created. We need to update [the documentation](https://www.kubeflow.org/docs/components/multi-tenancy/getting-started/#manual-profile-creation).

Example `LimitRange`:
```yaml
apiVersion: v1
kind: LimitRange
metadata:
  name: <user>-limit-range
spec:
  limits:
  - default:
      cpu: 0.5
      memory: 512Mi
    defaultRequest:
      cpu: 0.01
      memory: 32Mi
    type: Container
```

Which can be applied a user namespace:
```bash
kubectl apply -f <yaml> -n <user>
```

/cc @chensun @Linchin 

_Originally posted by @gkcalat in https://github.com/kubeflow/pipelines/issues/9089#issuecomment-1499665846_
