### ISSUE TITLE
Broken Link presubmit test

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#73]
A broken link check is described in 
https://github.com/kubeflow/website/issues/62#issuecomment-401168561

Can we run that as a presubmit test?

**Comment by scottilee** [comment]
I will add the following to the `kubeflow/website section of the presubmits when https://github.com/kubernetes/test-infra/issues/14343 is resolved:
```
  - name: kubeflow-website-link-check
    cluster: kubeflow
    always_run: true         # Run for every PR, or only when requested.
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: registry.hub.docker.com/ktbartholomew/link-checker:latest
        imagePullPolicy: Always
    annotations:
      testgrid-dashboards: sig-big-data
      description: Presubmits for kubeflow/website.
      testgrid-num-columns-recent: '30'
```

Although I'm not sure if it's okay if the image is not stored in gcr.io?
